peripheral_name: "example_peripheral"

spreadsheet_path: "./spreadsheets/example_spreadsheet.xlsx"

rtl_output_dir: "./example_destination"

tb_output_dir: "./example_destination"

package_output_dir: "./example_destination"

macro_output_dir: "./example_destination"

cdef_output_dir: "./example_destination"

script_output_dir: "./example_destination"

sim_output_dir: "./example_destination"
